[workspace]
members = ["proxy", "shred_protos"]
resolver = "2"

[workspace.package]
version = "0.3.0"
description = "Forward-only UDP shred relay: receives shreds on a bound port and forwards them to local consumers."
authors = ["Raiku <engineering@raiku.com>"]
homepage = "https://raiku.com/"
edition = "2021"

[workspace.dependencies]
arc-swap = "1.6"
clap = { version = "4", features = ["derive", "env"] }
crossbeam-channel = "0.5.8"
dashmap = "5"
env_logger = "0.11"
hostname = "0.4.0"
itertools = "0.14.0"
log = "0.4"
prost = "0.13"
prost-build = "0.13"
prost-types = "0.13"
raiku-shred-protos = { path = "shred_protos" }
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
signal-hook = "0.3"
solana-client = "=2.2.1"
solana-metrics = "=2.2.1"
solana-net-utils = "=2.2.1"
solana-perf = "=2.2.1"
solana-sdk = "=2.2.1"
solana-streamer = "=2.2.1"
thiserror = "2"

[profile.release]
# thin has minimal overhead vs none (default): https://blog.llvm.org/2016/06/thinlto-scalable-and-incremental-lto.html
lto = "thin"
