[package]
name = "raiku-shred-protos"
version = { workspace = true }
description = "Protobuf messages used by the Raiku shred forwarder"
authors = { workspace = true }
homepage = { workspace = true }
edition = { workspace = true }
publish = false

[dependencies]
prost = { workspace = true }
prost-types = { workspace = true }

[build-dependencies]
protobuf-src = "1"
prost-build = { workspace = true }
