[package]
name = "raiku-shredstream-proxy"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
edition = { workspace = true }

[dependencies]
arc-swap = { workspace = true }
clap = { workspace = true }
crossbeam-channel = { workspace = true }
dashmap = { workspace = true }
env_logger = { workspace = true }
hostname = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
prost = { workspace = true }
raiku-shred-protos = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
signal-hook = { workspace = true }
solana-client = { workspace = true }
solana-metrics = { workspace = true }
solana-net-utils = { workspace = true }
solana-perf = { workspace = true }
solana-sdk = { workspace = true }
solana-streamer = { workspace = true }
thiserror = { workspace = true }
