name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          caller-workflow-name: release

      - name: Clippy check
        run: cargo clippy --all-features --all-targets --tests -- -D warnings

      - name: Build release binary
        run: |
          cargo build --release --bin raiku-shredstream-proxy
          cp target/release/raiku-shredstream-proxy \
             ./raiku-shredstream-proxy-x86_64-unknown-linux-gnu
          file ./raiku-shredstream-proxy-x86_64-unknown-linux-gnu

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./raiku-shredstream-proxy-x86_64-unknown-linux-gnu
